# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

alias(
    name = "stdout_logger",
    actual = "//score/mw/log/rust/stdout_logger:stdout_logger",
    deprecation = "//score/log_rust/stdout_logger:stdout_logger has moved to //score/mw/log/rust/stdout_logger:stdout_logger. " +
                  "Update your dependency to the new //score/mw/... label.",
    visibility = ["//visibility:public"],
)
