# Workflow configuration for S-CORE CI - Release Check
# This workflow runs Bazel build and test when triggered by tag creation.

name: Bazel Build & Test baselibs (with host toolchain GCC12.2)
on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0
      - 'release-*' # Triggers on release tags like release-1.0.0

permissions:
  contents: write

jobs:
  build_host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
      - name: Bazel build baselibs targets
        run: |
          bazel build --config bl-x86_64-linux -- //score/...
  build_qnx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
      - name: Bazel build baselibs targets
        run: |
          bazel build --config bl-x86_64-linux -- //score/...
  test_host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
      - name: Bazel test baselibs targets
        run: |
          bazel test --config bl-x86_64-linux //score/... -- \
          -//score/language/safecpp/aborts_upon_exception:abortsuponexception_toolchain_test \
          -//score/containers:dynamic_array_test
  release_verification:
    runs-on: ubuntu-latest
    needs: [build_host, build_target, test_host]
    if: always() && (needs.build_host.result == 'failure' || needs.build_target.result == 'failure' || needs.test_host.result == 'failure')
    steps:
      - name: Remove release and tag (if exists)
        uses: nikhilbadyal/ghaction-rm-releases@v0.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_PATTERN: ${{ github.ref_name }}

